# Generated by Django 3.0.2 on 2020-05-13 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_hex', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(default='', max_length=20)),
                ('player_pass', models.CharField(default='', max_length=20)),
                ('player_lvl', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(default='', max_length=50)),
                ('room_desc', models.CharField(default='', max_length=500)),
                ('room_c1', models.CharField(default='', max_length=1000)),
                ('room_c2', models.CharField(default='', max_length=1000)),
                ('room_c3', models.CharField(default='', max_length=1000)),
                ('room_c1_a', models.CharField(default='', max_length=5)),
                ('room_c2_a', models.CharField(default='', max_length=5)),
                ('room_c3_a', models.CharField(default='', max_length=5)),
                ('room_choiceCount', models.IntegerField(blank=True, null=True)),
                ('room_type', models.IntegerField(blank=True, null=True)),
                ('room_desc_alt', models.CharField(default='', max_length=500)),
                ('room_back', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
